### ISSUE TITLE
A question about usage

### ISSUE THREAD

**Issue by sunscreem** [mvdnbrk/laravel-mix-tailwindcss#1]
Hello, Sorry for asking a really dumb question.

Why would I use this? I've been using mix and tailwind for a while now and noticed this yesterday :)

**Comment by mvdnbrk** [comment]
- Figures out which config file to load; `tailwind.config.js` or `tailwind.js` for versions <= 1.0.
- Takes care of issue with `processCssUrls` for sass users.

`mix.tailwind()` and your done.

Offcourse your are free to use one of the other options as you can find in the Tailwind [installation instructions for Mix](https://tailwindcss.com/docs/installation/#laravel-mix).

**Comment by sunscreem** [comment]
Thank you @mvdnbrk - that's great. Will be using this going forward :)
