### ISSUE TITLE
TypeError: Mix.seesNpmPackage is not a function

### ISSUE THREAD

**Issue by iamjohnpeet** [mvdnbrk/laravel-mix-tailwindcss#3]
**Issue**
When using PostCSS I get an error when running `npm watch`...

"if (Mix.components.has('postCss') && Mix.seesNpmPackage('postcss-import')) {..."
"TypeError: Mix.seesNpmPackage is not a function"

**Dependancies Versions**
```
    "@tailwindcss/custom-forms": "^0.2.0",
    "laravel-mix": "^2.1.14",
    "mix-tailwindcss": "^1.2.0",
    "postcss-import": "^12.0.1",
    "tailwindcss": "^1.1.4",
    "vue": "^2.6.11"
```

**Comment by mvdnbrk** [comment]
Update `laravel-mix` 😉
